In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import ast

In [4]:
data = pd.read_csv('data/kickstarter.csv')
data.head()

,id,name,blurb,goal,pledged,state,slug,country,country_displayable_name,currency,...,category,video,profile,spotlight,urls,percent_funded,is_liked,is_disliked,is_launched,prelaunch_activated
0,386902354,MY LITTLE PONY: Friendship is Magic Rainbow Co...,The sparkliest and most iconic moments from th...,25000.0,64002.0,live,my-little-pony-friendship-is-magic-rainbow-col...,US,the United States,USD,...,"{'id': 250, 'name': 'Comic Books', 'analytics_...",NaN,"{'id': 5279484, 'project_id': 5279484, 'state'...",False,{'web': {'project': 'https://www.kickstarter.c...,256.008000,False,False,True,True
1,632098548,How to THINK when you DRAW BOOK 9 + REPRINTS +...,The 9th 200 PAGE BOOK of Lorenzo Etherington's...,1000.0,341824.0,live,how-to-think-when-you-draw-book-9-reprints-ink...,GB,the United Kingdom,GBP,...,"{'id': 3, 'name': 'Comics', 'analytics_name': ...","{'id': 1413171, 'status': 'successful', 'hls':...","{'id': 5325805, 'project_id': 5325805, 'state'...",False,{'web': {'project': 'https://www.kickstarter.c...,34182.400000,False,False,True,False
2,1058096422,stare down. Volumes 1 & 2,"The story of Nil, who misconstrues an enamoure...",3000.0,8581.0,live,stare-down-webtoon-volumes-1-and-2,US,the United States,USD,...,"{'id': 252, 'name': 'Graphic Novels', 'analyti...","{'id': 1423417, 'status': 'successful', 'hls':...","{'id': 5329619, 'project_id': 5329619, 'state'...",False,{'web': {'project': 'https://www.kickstarter.c...,286.033333,False,False,True,True
3,559582035,Tales of Asunda Tome + New Untamed Comic & D&D...,StrangerComics PRESENTS: Deluxe Fantasy Omnibu...,10000.0,89828.0,live,the-untamed-wishing-well-1-tales-of-asunda-tome,US,the United States,USD,...,"{'id': 252, 'name': 'Graphic Novels', 'analyti...","{'id': 1421552, 'status': 'successful', 'hls':...","{'id': 5313352, 'project_id': 5313352, 'state'...",False,{'web': {'project': 'https://www.kickstarter.c...,898.280000,False,False,True,True
4,1828445616,Hallowed Ground - An Afterlife Horror Comic An...,A 100+ Page Horror Anthology. Twelve stories o...,35000.0,10417.0,live,afterlife1,US,the United States,USD,...,"{'id': 252, 'name': 'Graphic Novels', 'analyti...",NaN,"{'id': 5315571, 'project_id': 5315571, 'state'...",False,{'web': {'project': 'https://www.kickstarter.c...,29.762857,False,False,True,True

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 40 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  17996 non-null  int64
 1   name                                17996 non-null  str
 2   blurb                               17986 non-null  str
 3   goal                                17996 non-null  float64
 4   pledged                             17996 non-null  float64
 5   state                               17996 non-null  str
 6   slug                                17996 non-null  str
 7   country                             17996 non-null  str
 8   country_displayable_name            17996 non-null  str
 9   currency                            17996 non-null  str
 10  currency_symbol                     17996 non-null  str
 11  currency_trailing_code              17996 non-null  bool
 12  deadline                            17996 non-null  int64
 13  state_changed_at                    17996 non-null  int64
 14  created_at                          17996 non-null  int64
 15  launched_at                         17996 non-null  int64
 16  is_in_post_campaign_pledging_phase  17996 non-null  bool
 17  staff_pick                          17996 non-null  bool
 18  is_starrable                        17996 non-null  bool
 19  disable_communication               17996 non-null  bool
 20  backers_count                       17996 non-null  int64
 21  static_usd_rate                     17996 non-null  float64
 22  usd_pledged                         15241 non-null  float64
 23  converted_pledged_amount            15241 non-null  float64
 24  fx_rate                             17996 non-null  float64
 25  usd_exchange_rate                   15241 non-null  float64
 26  current_currency                    17996 non-null  str
 27  usd_type                            17996 non-null  str
 28  creator                             17996 non-null  str
 29  location                            17865 non-null  str
 30  category                            17996 non-null  str
 31  video                               13274 non-null  str
 32  profile                             17996 non-null  str
 33  spotlight                           17996 non-null  bool
 34  urls                                17996 non-null  str
 35  percent_funded                      17996 non-null  float64
 36  is_liked                            17996 non-null  bool
 37  is_disliked                         17996 non-null  bool
 38  is_launched                         17996 non-null  bool
 39  prelaunch_activated                 17996 non-null  bool
dtypes: bool(10), float64(8), int64(6), str(16)
memory usage: 4.3 MB

In [6]:
data.duplicated().sum()

np.int64(0)

дубликатов нет)

Сначала избавимся от признаков, которые не несут для нашей задачи пользы
удаляем:   
 6   slug - Часть URL-адреса проекта (то, что идет после домена) Используется для формирования красивых ссылок                        
 10  currency_symbol - Символ валюты                        
 11  currency_trailing_code - True/False Обычно значит, пишется ли символ валюты после суммы (как 100$) или до (как $100)                         
 18  is_starrable - Можно ли поставить «звезду» (добавить в избранное)                          
 19  disable_communication - Запрещено ли общение в комментариях (True/False)     
 21  static_usd_rate - Курс конвертации местной валюты в USD на момент создания проекта (фиксируется, чтобы курс не прыгал)  
 22  usd_pledged - Собранная сумма, пересчитанная в USD (может быть пропущена, если проект не собирал в USD)              
 23  converted_pledged_amount - Дублирует usd_pledged с учетом фиксированного курса платформы                               
 25  usd_exchange_rate - Курс обмена к USD (иногда отличается от `fx_rate` методикой расчета)         
 26  current_currency - Валюта, в которой сейчас отображаются суммы на странице(везде USD)                
 27  usd_type - Тип конвертации в USD                                   
 29  location - Данные о городе                             
 32  profile - Дополнительные настройки профиля  
 34  urls - Ссылки на веб-версию проекта и страницу наград                                    
 36  is_liked / 37  is_disliked Лайкнул/дизлайкнул ли текущий пользователь

In [7]:
data = data.drop(['slug', 'currency_symbol','currency_trailing_code','is_starrable','disable_communication','converted_pledged_amount','usd_exchange_rate','current_currency','usd_type','profile','is_liked','is_disliked','usd_pledged','location','static_usd_rate','urls'], axis=1)

In [8]:
data.head(5)

,id,name,blurb,goal,pledged,state,country,country_displayable_name,currency,deadline,...,staff_pick,backers_count,fx_rate,creator,category,video,spotlight,percent_funded,is_launched,prelaunch_activated
0,386902354,MY LITTLE PONY: Friendship is Magic Rainbow Co...,The sparkliest and most iconic moments from th...,25000.0,64002.0,live,US,the United States,USD,1777572005,...,True,173,1.000000,"{'id': 1690343815, 'name': 'BOOM! Studios', 's...","{'id': 250, 'name': 'Comic Books', 'analytics_...",NaN,False,256.008000,True,True
1,632098548,How to THINK when you DRAW BOOK 9 + REPRINTS +...,The 9th 200 PAGE BOOK of Lorenzo Etherington's...,1000.0,341824.0,live,GB,the United Kingdom,GBP,1775502000,...,True,3926,1.320012,"{'id': 1378058646, 'name': 'Lorenzo Etheringto...","{'id': 3, 'name': 'Comics', 'analytics_name': ...","{'id': 1413171, 'status': 'successful', 'hls':...",False,34182.400000,True,False
2,1058096422,stare down. Volumes 1 & 2,"The story of Nil, who misconstrues an enamoure...",3000.0,8581.0,live,US,the United States,USD,1777489656,...,True,119,1.000000,"{'id': 769898516, 'name': 'Rocketship', 'slug'...","{'id': 252, 'name': 'Graphic Novels', 'analyti...","{'id': 1423417, 'status': 'successful', 'hls':...",False,286.033333,True,True
3,559582035,Tales of Asunda Tome + New Untamed Comic & D&D...,StrangerComics PRESENTS: Deluxe Fantasy Omnibu...,10000.0,89828.0,live,US,the United States,USD,1776704517,...,True,408,1.000000,"{'id': 1182319554, 'name': 'Sebastian A. Jones...","{'id': 252, 'name': 'Graphic Novels', 'analyti...","{'id': 1421552, 'status': 'successful', 'hls':...",False,898.280000,True,True
4,1828445616,Hallowed Ground - An Afterlife Horror Comic An...,A 100+ Page Horror Anthology. Twelve stories o...,35000.0,10417.0,live,US,the United States,USD,1776996000,...,True,224,1.000000,"{'id': 1376978156, 'name': 'Deathline (from Li...","{'id': 252, 'name': 'Graphic Novels', 'analyti...",NaN,False,29.762857,True,True

Проверяем на пропуски:

In [9]:
data.isna().sum()

id                                       0
name                                     0
blurb                                   10
goal                                     0
pledged                                  0
state                                    0
country                                  0
country_displayable_name                 0
currency                                 0
deadline                                 0
state_changed_at                         0
created_at                               0
launched_at                              0
is_in_post_campaign_pledging_phase       0
staff_pick                               0
backers_count                            0
fx_rate                                  0
creator                                  0
category                                 0
video                                 4722
spotlight                                0
percent_funded                           0
is_launched                              0
prelaunch_activated                      0
dtype: int64

Пропуски в blurb значат, что просто нет описания у проекта. Такое бывает, это не ошибка. Автор просто решил, что он без описания все соберет
Пропуски в video также не являются ошибкой. Значит, у проекта нет прикрепленного видео

In [10]:
data['video'] = data['video'].fillna('')  #дальше пригодится
data['blurb'] = data['blurb'].fillna('')

In [11]:
# перводим в формат даты то, что является датой
data['state_changed_at'] = pd.to_datetime(data['state_changed_at'],unit='s')
data['deadline'] = pd.to_datetime(data['deadline'],unit='s')
data['created_at'] = pd.to_datetime(data['created_at'],unit='s')
data['launched_at'] = pd.to_datetime(data['launched_at'],unit='s')

теперь раскроем все вложенные данные

In [12]:
data['creator']

0        {'id': 1690343815, 'name': 'BOOM! Studios', 's...
1        {'id': 1378058646, 'name': 'Lorenzo Etheringto...
2        {'id': 769898516, 'name': 'Rocketship', 'slug'...
3        {'id': 1182319554, 'name': 'Sebastian A. Jones...
4        {'id': 1376978156, 'name': 'Deathline (from Li...
                               ...
17991    {'id': 787851171, 'name': 'Legends of Hapax', ...
17992    {'id': 1263999445, 'name': 'Dungeons & Dreadno...
17993    {'id': 437928348, 'name': '涼宮隼十 / パトスプロジェクト', ...
17994    {'id': 278762704, 'name': 'ASM-Games', 'slug':...
17995    {'id': 1170592379, 'name': 'Ross Cowman', 'slu...
Name: creator, Length: 17996, dtype: str

In [13]:
data['creator'] = data['creator'].apply(ast.literal_eval)
creator_df = pd.json_normalize(data['creator'])
creator_df

,id,name,slug,is_registered,is_email_verified,chosen_currency,is_superbacker,has_admin_message_badge,partner_badge,ppo_has_action,backing_action_count,avatar.thumb,avatar.small,avatar.medium,urls.web.user,urls.api.user,is_ksr_admin
0,1690343815,BOOM! Studios,boom-studios,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/052/388/145/a...,https://i.kickstarter.com/assets/052/388/145/a...,https://i.kickstarter.com/assets/052/388/145/a...,https://www.kickstarter.com/profile/boom-studios,https://api.kickstarter.com/v1/users/169034381...,NaN
1,1378058646,Lorenzo Etherington,thinkdraw7,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/052/498/845/c...,https://i.kickstarter.com/assets/052/498/845/c...,https://i.kickstarter.com/assets/052/498/845/c...,https://www.kickstarter.com/profile/thinkdraw7,https://api.kickstarter.com/v1/users/137805864...,NaN
2,769898516,Rocketship,rocketship,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/024/347/567/1...,https://i.kickstarter.com/assets/024/347/567/1...,https://i.kickstarter.com/assets/024/347/567/1...,https://www.kickstarter.com/profile/rocketship,https://api.kickstarter.com/v1/users/769898516...,NaN
3,1182319554,Sebastian A. Jones,sebastianajones,None,None,None,None,False,NaN,True,7,https://i.kickstarter.com/assets/007/417/981/0...,https://i.kickstarter.com/assets/007/417/981/0...,https://i.kickstarter.com/assets/007/417/981/0...,https://www.kickstarter.com/profile/sebastiana...,https://api.kickstarter.com/v1/users/118231955...,NaN
4,1376978156,Deathline (from Lifeline Comics),deathline,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/050/952/772/3...,https://i.kickstarter.com/assets/050/952/772/3...,https://i.kickstarter.com/assets/050/952/772/3...,https://www.kickstarter.com/profile/deathline,https://api.kickstarter.com/v1/users/137697815...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,787851171,Legends of Hapax,projectapax,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/041/228/299/8...,https://i.kickstarter.com/assets/041/228/299/8...,https://i.kickstarter.com/assets/041/228/299/8...,https://www.kickstarter.com/profile/projectapax,https://api.kickstarter.com/v1/users/787851171...,NaN
17992,1263999445,Dungeons & Dreadnoughts,dungeonndreadnought,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/047/951/813/c...,https://i.kickstarter.com/assets/047/951/813/c...,https://i.kickstarter.com/assets/047/951/813/c...,https://www.kickstarter.com/profile/dungeonndr...,https://api.kickstarter.com/v1/users/126399944...,NaN
17993,437928348,涼宮隼十 / パトスプロジェクト,pathosproject,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/045/857/675/b...,https://i.kickstarter.com/assets/045/857/675/b...,https://i.kickstarter.com/assets/045/857/675/b...,https://www.kickstarter.com/profile/pathosproject,https://api.kickstarter.com/v1/users/437928348...,NaN
17994,278762704,ASM-Games,asm-games,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/032/012/812/4...,https://i.kickstarter.com/assets/032/012/812/4...,https://i.kickstarter.com/assets/032/012/812/4...,https://www.kickstarter.com/profile/asm-games,https://api.kickstarter.com/v1/users/278762704...,NaN
17995,1170592379,Ross Cowman,rosscowman,None,None,None,None,False,NaN,False,0,https://i.kickstarter.com/assets/006/046/523/9...,https://i.kickstarter.com/assets/006/046/523/9...,https://i.kickstarter.com/assets/006/046/523/9...,https://www.kickstarter.com/profile/rosscowman,https://api.kickstarter.com/v1/users/117059237...,NaN

добавим в наш датасет только нужные столбцы

In [14]:
creator_df = creator_df.add_prefix('creator_')
data = pd.concat([data, creator_df['creator_id']], axis=1)
data = pd.concat([data, creator_df['creator_name']], axis=1)
data = pd.concat([data, creator_df['creator_is_registered']], axis=1)
data = pd.concat([data, creator_df['creator_is_ksr_admin']], axis=1)
data = pd.concat([data, creator_df['creator_is_superbacker']], axis=1)

In [15]:
data['category'] = data['category'].apply(ast.literal_eval)
category_df = pd.json_normalize(data['category'])
category_df

,id,name,analytics_name,slug,position,parent_id,parent_name,color,urls.web.discover
0,250,Comic Books,Comic Books,comics/comic books,2,3.0,Comics,16776056,http://www.kickstarter.com/discover/categories...
1,3,Comics,Comics,comics,2,NaN,NaN,16776056,http://www.kickstarter.com/discover/categories...
2,252,Graphic Novels,Graphic Novels,comics/graphic novels,4,3.0,Comics,16776056,http://www.kickstarter.com/discover/categories...
3,252,Graphic Novels,Graphic Novels,comics/graphic novels,4,3.0,Comics,16776056,http://www.kickstarter.com/discover/categories...
4,252,Graphic Novels,Graphic Novels,comics/graphic novels,4,3.0,Comics,16776056,http://www.kickstarter.com/discover/categories...
...,...,...,...,...,...,...,...,...,...
17991,35,Video Games,Video Games,games/video games,7,12.0,Games,51627,http://www.kickstarter.com/discover/categories...
17992,34,Tabletop Games,Tabletop Games,games/tabletop games,6,12.0,Games,51627,http://www.kickstarter.com/discover/categories...
17993,34,Tabletop Games,Tabletop Games,games/tabletop games,6,12.0,Games,51627,http://www.kickstarter.com/discover/categories...
17994,35,Video Games,Video Games,games/video games,7,12.0,Games,51627,http://www.kickstarter.com/discover/categories...
17995,34,Tabletop Games,Tabletop Games,games/tabletop games,6,12.0,Games,51627,http://www.kickstarter.com/discover/categories...

In [16]:
category_df = category_df.add_prefix('category_')
data = pd.concat([data, category_df['category_id']], axis=1)
data = pd.concat([data, category_df['category_name']], axis=1)
data = pd.concat([data, category_df['category_slug']], axis=1)
data = pd.concat([data, category_df['category_parent_id']], axis=1)
data = pd.concat([data, category_df['category_parent_name']], axis=1)

In [17]:
data['video']= data['video'][data['video']!=""].apply(ast.literal_eval)
video_df = pd.json_normalize(data['video'])
video_df

,id,status,hls,hls_type,high,high_type,base,base_type,tracks,width,height,frame
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1413171.0,successful,https://v2.kickstarter.com/1774905984-BtmLSvI1...,application/x-mpegURL,https://v2.kickstarter.com/1774905984-BtmLSvI1...,"video/mp4; codecs=""avc1.64001E, mp4a.40.2""",https://v2.kickstarter.com/1774905984-BtmLSvI1...,"video/mp4; codecs=""avc1.42E01E, mp4a.40.2""",[],1280.0,720.0,https://d15chbti7ht62o.cloudfront.net/projects...
2,1423417.0,successful,https://v2.kickstarter.com/1774901730-LMFhnhqA...,application/x-mpegURL,https://v2.kickstarter.com/1774901730-LMFhnhqA...,"video/mp4; codecs=""avc1.64001E, mp4a.40.2""",https://v2.kickstarter.com/1774901730-LMFhnhqA...,"video/mp4; codecs=""avc1.42E01E, mp4a.40.2""",[],1280.0,720.0,https://d15chbti7ht62o.cloudfront.net/projects...
3,1421552.0,successful,https://v2.kickstarter.com/1774982023-DW8K0B4u...,application/x-mpegURL,https://v2.kickstarter.com/1774982023-DW8K0B4u...,"video/mp4; codecs=""avc1.64001E, mp4a.40.2""",https://v2.kickstarter.com/1774982023-DW8K0B4u...,"video/mp4; codecs=""avc1.42E01E, mp4a.40.2""",[],1280.0,720.0,https://d15chbti7ht62o.cloudfront.net/projects...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
17991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
video_df = video_df.add_prefix('video_')
data = pd.concat([data, video_df['video_id']], axis=1)

уиии такая умнички, идем дальше, надо убить все то, что разложили на части

In [19]:
data = data.drop(['creator','category','video'], axis=1)

In [20]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  17996 non-null  int64
 1   name                                17996 non-null  str
 2   blurb                               17996 non-null  str
 3   goal                                17996 non-null  float64
 4   pledged                             17996 non-null  float64
 5   state                               17996 non-null  str
 6   country                             17996 non-null  str
 7   country_displayable_name            17996 non-null  str
 8   currency                            17996 non-null  str
 9   deadline                            17996 non-null  datetime64[s]
 10  state_changed_at                    17996 non-null  datetime64[s]
 11  created_at                          17996 non-null  datetime64[s]
 12  launched_at                         17996 non-null  datetime64[s]
 13  is_in_post_campaign_pledging_phase  17996 non-null  bool
 14  staff_pick                          17996 non-null  bool
 15  backers_count                       17996 non-null  int64
 16  fx_rate                             17996 non-null  float64
 17  spotlight                           17996 non-null  bool
 18  percent_funded                      17996 non-null  float64
 19  is_launched                         17996 non-null  bool
 20  prelaunch_activated                 17996 non-null  bool
 21  creator_id                          17996 non-null  int64
 22  creator_name                        17996 non-null  str
 23  creator_is_registered               0 non-null      object
 24  creator_is_ksr_admin                3 non-null      object
 25  creator_is_superbacker              0 non-null      object
 26  category_id                         17996 non-null  int64
 27  category_name                       17996 non-null  str
 28  category_slug                       17996 non-null  str
 29  category_parent_id                  14004 non-null  float64
 30  category_parent_name                14004 non-null  str
 31  video_id                            13274 non-null  float64
dtypes: bool(5), datetime64[s](4), float64(6), int64(4), object(3), str(10)
memory usage: 3.8+ MB

In [21]:
data.duplicated().sum()

np.int64(1933)

как так то... надо глянуть

In [22]:
data[data.duplicated(keep=False)].sort_values(by = 'id' )

,id,name,blurb,goal,pledged,state,country,country_displayable_name,currency,deadline,...,creator_name,creator_is_registered,creator_is_ksr_admin,creator_is_superbacker,category_id,category_name,category_slug,category_parent_id,category_parent_name,video_id
14888,1594224,KeyStone A Cappella's Debut Album!,KeyStone A Cappella is recording our debut alb...,5000.0,8173.0,successful,US,the United States,USD,2014-09-01 03:59:00,...,KeyStone A Cappella,None,NaN,None,14,Music,music,NaN,NaN,406027.0
14587,1594224,KeyStone A Cappella's Debut Album!,KeyStone A Cappella is recording our debut alb...,5000.0,8173.0,successful,US,the United States,USD,2014-09-01 03:59:00,...,KeyStone A Cappella,None,NaN,None,14,Music,music,NaN,NaN,406027.0
14025,4202650,Ron Hall's Memphis: The Rock 'n Roll Years His...,Ron Hall's newest Memphis history book product...,3000.0,3063.0,successful,US,the United States,USD,2014-05-09 03:21:16,...,Sherman Willmott,None,NaN,None,43,Rock,music/rock,14.0,Music,352428.0
14912,4202650,Ron Hall's Memphis: The Rock 'n Roll Years His...,Ron Hall's newest Memphis history book product...,3000.0,3063.0,successful,US,the United States,USD,2014-05-09 03:21:16,...,Sherman Willmott,None,NaN,None,43,Rock,music/rock,14.0,Music,352428.0
15336,4202650,Ron Hall's Memphis: The Rock 'n Roll Years His...,Ron Hall's newest Memphis history book product...,3000.0,3063.0,successful,US,the United States,USD,2014-05-09 03:21:16,...,Sherman Willmott,None,NaN,None,43,Rock,music/rock,14.0,Music,352428.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,2143246629,Into The Well: Reclaiming the Stage as Sacred,Immersive dance production: A psychosexual thr...,45000.0,45021.0,successful,US,the United States,USD,2025-07-20 14:10:37,...,Sabina Lundgren,None,NaN,None,255,Residencies,dance/residencies,6.0,Dance,1366756.0
16023,2145544279,Future Boyfriend,A short comedic film about falling in love in ...,10000.0,12645.0,successful,US,the United States,USD,2014-08-05 07:00:00,...,Emily Bell and Ron Morehouse,None,NaN,None,292,Comedy,film & video/comedy,11.0,Film & Video,412770.0
5745,2145544279,Future Boyfriend,A short comedic film about falling in love in ...,10000.0,12645.0,successful,US,the United States,USD,2014-08-05 07:00:00,...,Emily Bell and Ron Morehouse,None,NaN,None,292,Comedy,film & video/comedy,11.0,Film & Video,412770.0
7775,2146767304,Unmethodical,A collection of some of my favorite photograph...,250.0,545.0,successful,US,the United States,USD,2021-05-31 01:00:00,...,Brian White,None,NaN,None,277,Nature,photography/nature,15.0,Photography,NaN
7773,2146767304,Unmethodical,A collection of some of my favorite photograph...,250.0,545.0,successful,US,the United States,USD,2021-05-31 01:00:00,...,Brian White,None,NaN,None,277,Nature,photography/nature,15.0,Photography,NaN

в строках были различия только внуутри словарей, но по сути проекты идентичны, так что придется поудалять дубли

In [23]:
data = data.drop_duplicates()
data.info()

<class 'pandas.DataFrame'>
Index: 16063 entries, 0 to 17995
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  16063 non-null  int64
 1   name                                16063 non-null  str
 2   blurb                               16063 non-null  str
 3   goal                                16063 non-null  float64
 4   pledged                             16063 non-null  float64
 5   state                               16063 non-null  str
 6   country                             16063 non-null  str
 7   country_displayable_name            16063 non-null  str
 8   currency                            16063 non-null  str
 9   deadline                            16063 non-null  datetime64[s]
 10  state_changed_at                    16063 non-null  datetime64[s]
 11  created_at                          16063 non-null  datetime64[s]
 12  launched_at                         16063 non-null  datetime64[s]
 13  is_in_post_campaign_pledging_phase  16063 non-null  bool
 14  staff_pick                          16063 non-null  bool
 15  backers_count                       16063 non-null  int64
 16  fx_rate                             16063 non-null  float64
 17  spotlight                           16063 non-null  bool
 18  percent_funded                      16063 non-null  float64
 19  is_launched                         16063 non-null  bool
 20  prelaunch_activated                 16063 non-null  bool
 21  creator_id                          16063 non-null  int64
 22  creator_name                        16063 non-null  str
 23  creator_is_registered               0 non-null      object
 24  creator_is_ksr_admin                3 non-null      object
 25  creator_is_superbacker              0 non-null      object
 26  category_id                         16063 non-null  int64
 27  category_name                       16063 non-null  str
 28  category_slug                       16063 non-null  str
 29  category_parent_id                  12638 non-null  float64
 30  category_parent_name                12638 non-null  str
 31  video_id                            11584 non-null  float64
dtypes: bool(5), datetime64[s](4), float64(6), int64(4), object(3), str(10)
memory usage: 3.5+ MB

In [24]:
data.isna().sum()

id                                        0
name                                      0
blurb                                     0
goal                                      0
pledged                                   0
state                                     0
country                                   0
country_displayable_name                  0
currency                                  0
deadline                                  0
state_changed_at                          0
created_at                                0
launched_at                               0
is_in_post_campaign_pledging_phase        0
staff_pick                                0
backers_count                             0
fx_rate                                   0
spotlight                                 0
percent_funded                            0
is_launched                               0
prelaunch_activated                       0
creator_id                                0
creator_name                              0
creator_is_registered                 16063
creator_is_ksr_admin                  16060
creator_is_superbacker                16063
category_id                               0
category_name                             0
category_slug                             0
category_parent_id                     3425
category_parent_name                   3425
video_id                               4479
dtype: int64

в столбцах  creator_is_registered и creator_is_superbacker полностью пусто, здесь creator_is_ksr_admin всего три значения. Совершенно не нужны нам((

  category_parent_id,category_parent_name - здесь пустоты, потому что категория является родителем сама по себе, поэтому ни на кого не ссылкается. Поэтому проставим здесь 0, так "мама" категория

In [25]:
data = data.drop(['creator_is_registered','creator_is_superbacker','creator_is_ksr_admin'], axis=1)

In [26]:
data['category_parent_id'] = data['category_parent_id'].fillna(0)
data['category_parent_name'] = data['category_parent_name'].fillna("0")

In [27]:
data.isna().sum()

id                                       0
name                                     0
blurb                                    0
goal                                     0
pledged                                  0
state                                    0
country                                  0
country_displayable_name                 0
currency                                 0
deadline                                 0
state_changed_at                         0
created_at                               0
launched_at                              0
is_in_post_campaign_pledging_phase       0
staff_pick                               0
backers_count                            0
fx_rate                                  0
spotlight                                0
percent_funded                           0
is_launched                              0
prelaunch_activated                      0
creator_id                               0
creator_name                             0
category_id                              0
category_name                            0
category_slug                            0
category_parent_id                       0
category_parent_name                     0
video_id                              4479
dtype: int64

In [28]:
data

,id,name,blurb,goal,pledged,state,country,country_displayable_name,currency,deadline,...,is_launched,prelaunch_activated,creator_id,creator_name,category_id,category_name,category_slug,category_parent_id,category_parent_name,video_id
0,386902354,MY LITTLE PONY: Friendship is Magic Rainbow Co...,The sparkliest and most iconic moments from th...,25000.0,64002.0,live,US,the United States,USD,2026-04-30 18:00:05,...,True,True,1690343815,BOOM! Studios,250,Comic Books,comics/comic books,3.0,Comics,NaN
1,632098548,How to THINK when you DRAW BOOK 9 + REPRINTS +...,The 9th 200 PAGE BOOK of Lorenzo Etherington's...,1000.0,341824.0,live,GB,the United Kingdom,GBP,2026-04-06 19:00:00,...,True,False,1378058646,Lorenzo Etherington,3,Comics,comics,0.0,0,1413171.0
2,1058096422,stare down. Volumes 1 & 2,"The story of Nil, who misconstrues an enamoure...",3000.0,8581.0,live,US,the United States,USD,2026-04-29 19:07:36,...,True,True,769898516,Rocketship,252,Graphic Novels,comics/graphic novels,3.0,Comics,1423417.0
3,559582035,Tales of Asunda Tome + New Untamed Comic & D&D...,StrangerComics PRESENTS: Deluxe Fantasy Omnibu...,10000.0,89828.0,live,US,the United States,USD,2026-04-20 17:01:57,...,True,True,1182319554,Sebastian A. Jones,252,Graphic Novels,comics/graphic novels,3.0,Comics,1421552.0
4,1828445616,Hallowed Ground - An Afterlife Horror Comic An...,A 100+ Page Horror Anthology. Twelve stories o...,35000.0,10417.0,live,US,the United States,USD,2026-04-24 02:00:00,...,True,True,1376978156,Deathline (from Lifeline Comics),252,Graphic Novels,comics/graphic novels,3.0,Comics,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,319939511,Legends of Hapax: the new turn-based RPG gener...,Legends Hapax is a game that draws on the grea...,0.0,0.0,submitted,ES,Spain,EUR,1970-01-01 00:00:00,...,False,True,787851171,Legends of Hapax,35,Video Games,games/video games,12.0,Games,NaN
17992,1792472318,Grimdark Battlefleet: Fleets of Midgard,Command mighty warfleets in the battle for Mid...,500.0,0.0,started,US,the United States,USD,1970-01-01 00:00:00,...,False,True,1263999445,Dungeons & Dreadnoughts,34,Tabletop Games,games/tabletop games,12.0,Games,NaN
17993,570470125,想刃のデュアレイド / Dual Blade of Postmortem Desires,デュアルストーリー型・抜刀剣戟カードゲーム,0.0,0.0,submitted,JP,Japan,JPY,1970-01-01 00:00:00,...,False,True,437928348,涼宮隼十 / パトスプロジェクト,34,Tabletop Games,games/tabletop games,12.0,Games,NaN
17994,1054211112,Oaths of Light - a 3D jrpg game where player c...,A JRPG in which you will go through Eden's jou...,0.0,0.0,submitted,FR,France,EUR,1970-01-01 00:00:00,...,False,True,278762704,ASM-Games,35,Video Games,games/video games,12.0,Games,NaN
17995,840223440,BFF! The Golden Years,A heartwarming tabletop rpg of elder lady frie...,25000.0,0.0,started,US,the United States,USD,1970-01-01 00:00:00,...,False,True,1170592379,Ross Cowman,34,Tabletop Games,games/tabletop games,12.0,Games,NaN