In [1]:
import requests
import pandas as pd
import time

In [2]:
API_key = "hpSobUtXBHcPw37mqPR1J3ER"
request = "https://www.searchapi.io/api/v1/search"

In [3]:
params = {
    "engine": "ebay_search",
    "q": "comics",
    "ebay_domain": "ebay.com",
    "num": 60,
    "page": 1
}

page = requests.get(request, headers={'Authorization': f'Bearer {API_key}'}, params=params)
page

In [4]:
res = page.json()
res.keys()

dict_keys(['search_metadata', 'search_parameters', 'search_information', 'categories', 'filters', 'organic_results', 'related_searches', 'pagination'])

In [5]:
res["organic_results"][0]

{'position': 1,
 'item_id': '295102178301',
 'title': 'LARGE 25 COMICS BOOK LOT-MARVEL, DC, INDIES- FREE/Fast Shipping! VF to NM+ ALL',
 'link': 'https://www.ebay.com/itm/295102178301',
 'seller': {'name': 'hadleycomics',
  'reviews': 1600,
  'positive_feedback_percent': 99.8},
 'condition': 'New (Other)',
 'buying_format': 'or Best Offer',
 'extensions': ['Free returns',
  '1,248 sold',
  'Save up to 10% when you buy more'],
 'price': '$22.49',
 'extracted_price': 22.49,
 'original_price': '$24.99',
 'extracted_original_price': 24.99,
 'shipping': 'Located in United States',
 'deal': 'Free delivery in 2-4 days',
 'thumbnail': 'https://i.ebayimg.com/images/g/EmQAAOSwmLFmq7~I/s-l500.jpg'}

In [6]:
def clean_page_columns(page_df):
    page_df['seller_name'] = page_df['seller'].apply(lambda d: d['name'] if pd.notna(d) and 'name' in d else None)
    page_df['seller_reviews'] = page_df['seller'].apply(lambda d: d['reviews'] if pd.notna(d) and 'reviews' in d else None)
    page_df['seller_feedback'] = page_df['seller'].apply(lambda d: d['positive_feedback_percent'] if pd.notna(d) and 'positive_feedback_percent' in d else None)
    page_df['extensions'] = page_df['extensions'].fillna('')
    page_df['sold_text'] = page_df['extensions'].apply(lambda x: x[2] if isinstance(x, list) and len(x) > 2 else None)
    page_df['return_info'] = page_df['extensions'].apply(lambda x: x[1] if isinstance(x, list) and len(x) > 1 else None)
    page_df['location'] = page_df['extensions'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
    page_df.set_index('item_id', inplace=True)
    return page_df[['title', 'price', 'extracted_price', 'reviews', 'condition', 'buying_format', 'seller_name', 'seller_reviews', 'seller_feedback', 'sold_text', 'return_info', 'location', 'link']]

In [7]:
page_df = pd.DataFrame(res["organic_results"])
ebay_df_test = clean_page_columns(page_df)
ebay_df_test

,title,price,extracted_price,reviews,condition,buying_format,seller_name,seller_reviews,seller_feedback,sold_text,return_info,location,link
item_id,,,,,,,,,,,,,
295102178301,"LARGE 25 COMICS BOOK LOT-MARVEL, DC, INDIES- F...",$22.49,22.49,NaN,New (Other),or Best Offer,hadleycomics,1600,99.8,Save up to 10% when you buy more,"1,248 sold",Free returns,https://www.ebay.com/itm/295102178301
287039504394,DC Marvel Superman Spider-Man #1 (One Shot) Co...,$14.99,14.99,NaN,Brand New,Buy It Now,si-fi_toys,14400,99.6,None,187 sold,Free returns,https://www.ebay.com/itm/287039504394
284701338991,lot of 100 comics 80s 90s 2000 Marvel Dc Horse...,$28.95,28.95,NaN,Pre-Owned,Buy It Now,77kings,8200,99.9,None,"1,064 sold",Located in United States,https://www.ebay.com/itm/284701338991
227123160181,"Invincible Compendium 1, 2, & 3 Book Lot Compl...",$142.99,142.99,NaN,Brand New,Buy It Now,comicmaster4000,5800,99.2,None,93 sold,Located in United States,https://www.ebay.com/itm/227123160181
227289598146,Amazing Spider-Man (2025) #1-19 20 21 22 23 24...,$4.88 to $159.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,10% off $40+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/227289598146
336474481924,Absolute Batman 1 2 3 4 5 6 7 8 9 10 11 12 13 ...,$119.99,119.99,NaN,New (Other),Buy It Now,mccartycards,9100,99.8,None,61 sold,Located in United States,https://www.ebay.com/itm/336474481924
188257989469,Dead Samurai #6 Cover C Drax Gal Cover,$5.99,5.99,NaN,New (Other),or Best Offer,torpedocomics,7700,100.0,None,None,Located in United States,https://www.ebay.com/itm/188257989469
168293327141,Web Of Venom #1 (NM),$5.69,5.69,NaN,Brand New,Buy It Now,thecomicferret,13300,99.9,Almost gone,Free returns,Located in United States,https://www.ebay.com/itm/168293327141
156070129648,Godhood Comics The Antagonists NM-/M 2023,$119.95 to $149.95,NaN,NaN,Brand New,Buy It Now,multiversecomicsandmore,7200,100.0,None,None,Located in United States,https://www.ebay.com/itm/156070129648
168291163681,Marvel Comics ‘The Immortal Hulk Omnibus’ (202...,$79.89,79.89,NaN,Brand New,or Best Offer,melea3861,3900,99.4,None,54 watchers,Located in United States,https://www.ebay.com/itm/168291163681
197906847354,Marvel Comics Spider-Man Clone Saga Omnibus #1...,$38.00,38.00,1.0,Brand New,Buy It Now,funaticals,14600,99.9,None,727 sold,Located in United States,https://www.ebay.com/itm/197906847354
198240343057,Daredevil #1 True Believers Blind Bag Comic Bo...,$5.99,5.99,NaN,Brand New,Buy It Now,planetcomicsgvsc,9900,99.7,None,55 sold,Almost gone,https://www.ebay.com/itm/198240343057
298187492786,TRANSFORMERS #1 - COVER A - 1ST PRINT - DANIEL...,$36.00,36.00,NaN,Brand New,Buy It Now,phantomc77,1700,100.0,None,None,22 watchers,https://www.ebay.com/itm/298187492786
387100136486,Daredevil Black Armor #1 Marvel Comics CGC SS ...,$849.95,849.95,NaN,New (Other),or Best Offer,galaxycon,7300,99.7,None,58 watchers,Located in United States,https://www.ebay.com/itm/387100136486
166039533501,Deadpool #1 Limited series NM Marvel Comics,$16.31,16.31,NaN,NaN,or Best Offer,matthew6781,1400,98.7,None,20 watchers,Located in United States,https://www.ebay.com/itm/166039533501
166881476558,Ultimate Fallout 4 Mole Variant CGC 9.8,$200.00,200.00,NaN,NaN,or Best Offer,matthew6781,1400,98.7,None,40 watchers,Located in United States,https://www.ebay.com/itm/166881476558
227278448687,Daredevil (2026) #1 Marvel Comics COVER SELECT,$5.88 to $109.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,10% off $40+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/227278448687
227292224525,Everyone Loves a Jewel Thief (2026) #1 Ignitio...,$2.88 to $11.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,10% off $40+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/227292224525
267104165232,BACKSTOCK CLEANOUT! Lot Of 10 Books Mixed Titl...,$13.99,13.99,NaN,Pre-Owned,or Best Offer,the.atlanta.pickers,58500,99.8,250 sold,Free returns,Located in United States,https://www.ebay.com/itm/267104165232
366333574326,Fury of Firestorm 1A 2026 Stock Image,$3.99,3.99,NaN,NaN,Buy It Now,mycomicshop,579700,99.9,None,Free returns,Located in United States,https://www.ebay.com/itm/366333574326
197846707702,Marvel Comics Spider-Verse / Spider-Geddon 202...,$38.00,38.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,"1,034 sold",Located in United States,https://www.ebay.com/itm/197846707702
236740658175,The Fury of Firestorm #1 (DC Comics 2026) Main...,$3.40,3.40,NaN,Brand New,Buy It Now,originstory,25900,100.0,None,20% off 2+,Free returns,https://www.ebay.com/itm/236740658175
198050057954,MARVEL COMICS THE AVENGERS OMNIBUS VOL. 5 HC K...,$30.00,30.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,453 sold,Located in United States,https://www.ebay.com/itm/198050057954
198106622324,MARVEL COMICS X-23 OMNIBUS VOL. 1 HC CHOI COVER,$38.00,38.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,533 sold,Located in United States,https://www.ebay.com/itm/198106622324
277611270272,Marvel Teamup #14 Facsimile Edition Cover A Co...,$12.99,12.99,NaN,Brand New,Buy It Now,si-fi_toys,14400,99.6,None,149 sold,Free returns,https://www.ebay.com/itm/277611270272
366304094435,DC Marvel Superman Spider-Man 1A 2026 Stock Image,$8.19,8.19,NaN,NaN,Buy It Now,mycomicshop,579700,99.9,125 sold,Free returns,Located in United States,https://www.ebay.com/itm/366304094435
257433768997,Daredevil #1 True Believers Blind Bag Variant ...,$7.49,7.49,NaN,NaN,or Best Offer,randomstackscomics,29700,99.9,Almost gone,Free returns,Located in United States,https://www.ebay.com/itm/257433768997
197941615156,THOR by Straczynski & Gillen Omnibus REGULAR C...,$38.00,38.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,762 sold,Located in United States,https://www.ebay.com/itm/197941615156
205335563743,Marvel Comics Presents #1 Wolverine VFN/NM,$24.00,24.00,NaN,New (Other),or Best Offer,ultrasavvy777,79800,98.5,None,"Buy 1, get 1 15% off",Located in United States,https://www.ebay.com/itm/205335563743
145802185705,Detective Comics #332 CGC 5.0,$250.00,250.00,2.0,Pre-Owned,or Best Offer,baggy_men,291,100.0,None,39 watchers,Located in United States,https://www.ebay.com/itm/145802185705
186649040623,"Starwars #1,#2 & #3 In Hebrew Comics","$2,000.00",2000.00,NaN,New (Other),or Best Offer,digiartgal79,114,100.0,None,54 watchers,Located in United States,https://www.ebay.com/itm/186649040623
166039533423,X-Men #4 1st Omega Red NM- Marvel Comics,$32.20,32.20,NaN,NaN,or Best Offer,matthew6781,1400,98.7,None,None,Located in United States,https://www.ebay.com/itm/166039533423
167750340578,DC/Marvel Batman/Deadpool #1 CVR A Dan Mora (1...,$6.39,6.39,NaN,Brand New,Buy It Now,roninbrotherscomicss,10400,99.9,82 sold,Almost gone,Located in United States,https://www.ebay.com/itm/167750340578
157817435241,Web of Venom #1 Stefano Caselli Main Cover NM,$5.49,5.49,NaN,Brand New,Buy It Now,fantasynut1,24600,99.8,3 watchers,Free returns,Located in United States,https://www.ebay.com/itm/157817435241
366333630586,Iron Man #4A 2026 Stock Image,$4.99,4.99,NaN,NaN,Buy It Now,mycomicshop,579700,99.9,None,Free returns,Located in United States,https://www.ebay.com/itm/366333630586
277675341316,Spider-Man/Superman #1 (PRESALE 4/15/26) YOU P...,$7.99 to $55.00,NaN,NaN,Brand New,Buy It Now,412comics,14600,99.9,None,Free returns,Located in United States,https://www.ebay.com/itm/277675341316
227292287941,Teenage Mutant Ninja Turtles (2024) #1-14 15 1...,$4.88 to $299.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,10% off $40+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/227292287941
397817769603,DC Marvel Superman Spider-Man #1 Dell Otto Car...,$14.99,14.99,NaN,Brand New,Buy It Now,cherryhillcomics,1600,99.8,None,5 watchers,Located in United States,https://www.ebay.com/itm/397817769603
186750838333,Batman #65 1951 Golden Age Catwoman! GORGEOUS!,"$4,299.00",4299.00,NaN,Pre-Owned,or Best Offer,djac2007,1100,100.0,None,10 watchers,Located in United States,https://www.ebay.com/itm/186750838333
287209958612,Absolute Batman 1-18 1st Prints + Annual + Sig...,$625.00,625.00,NaN,Brand New,or Best Offer,gothamcollectibles,638,100.0,None,None,None,https://www.ebay.com/itm/287209958612
178010239055,DC/MARVEL SUPERMAN/SPIDER-MAN #1 LUCIO PARRILL...,$39.99,39.99,NaN,NaN,or Best Offer,krscomics,5400,100.0,None,40 watchers,Located in United States,https://www.ebay.com/itm/178010239055
286844274524,Absolute Batman #15 Cover A Nick Dragotta Firs...,$12.99,12.99,NaN,Brand New,Buy It Now,si-fi_toys,14400,99.6,None,"2,072 sold",Free returns,https://www.ebay.com/itm/286844274524
198037173815,MARVEL COMICS HOUSE OF M OMNIBUS COMPANION HC ...,$30.00,30.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,282 sold,Located in United States,https://www.ebay.com/itm/198037173815
227276437214,Marvel Team Up Facsimile Edition #14 (2026) Mc...,$7.50,7.50,NaN,Pre-Owned,Buy It Now,mcho6486,8600,100.0,None,17 sold,Located in United States,https://www.ebay.com/itm/227276437214
206196517918,Absolute Batman #19,$3.99,3.99,NaN,Brand New,Buy It Now,zonecomicsandtoys,26500,99.3,None,Free returns,Located in United States,https://www.ebay.com/itm/206196517918
366143317241,10x Skinbreaker #1 1st Print Cover A Robert Ki...,$19.99,19.99,NaN,Brand New,Buy It Now,nishastreasures,248,99.6,None,None,28 watchers,https://www.ebay.com/itm/366143317241
277775574973,Dorc #3 Cover A B C D Variant Set Options Imag...,$3.89 to $14.99,NaN,NaN,Brand New,Buy It Now,blazepccomics,18400,100.0,None,38+ sold,Located in United States,https://www.ebay.com/itm/277775574973
198005065984,THE AVENGERS OMNIBUS VOL. 1 HC ROMITA JR. COVE...,$30.00,30.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,524 sold,Located in United States,https://www.ebay.com/itm/198005065984
198069039038,FANTASTIC FOUR BY JOHN BYRNE OMNIBUS VOL. 1 HC...,$38.00,38.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,539 sold,Located in United States,https://www.ebay.com/itm/198069039038
198037173807,AMAZING SPIDER-MAN BY J. MICHAEL STRACZYNSKI O...,$38.00,38.00,NaN,Brand New,Buy It Now,funaticals,14600,99.9,None,600 sold,Located in United States,https://www.ebay.com/itm/198037173807
397752654066,LOT Of 100 Different Comics from a Comic Book ...,$49.99,49.99,NaN,Pre-Owned,or Best Offer,speedingbullet,5700,99.8,None,None,Located in United States,https://www.ebay.com/itm/397752654066
336281956243,"THE EASTER STORY #1 MARVEL COMICS.NOS , JESUS VF",$12.00,12.00,NaN,New (Other),or Best Offer,dimension9trade,534,100.0,Save up to 20% when you buy more,17 sold,Located in United States,https://www.ebay.com/itm/336281956243
186777198380,Dead Samurai #1 (Written by John Dolmayan) Cov...,$5.99,5.99,NaN,New (Other),Buy It Now,torpedocomics,7700,100.0,None,121 sold,Located in United States,https://www.ebay.com/itm/186777198380
227180687000,X-Men (2024) #1-13 14 15 16 17 18 19 20 21 22 ...,$4.88 to $119.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,19+ watchers,Free returns,Located in United States,https://www.ebay.com/itm/227180687000
227289692107,Iron Man (2026) #1 2 3 4 Marvel Comics COVER S...,$4.88 to $59.88,NaN,NaN,Brand New,Buy It Now,cosmic_kingdom_comics,15000,100.0,10% off $40+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/227289692107
236734485074,Iron Man #1-4 Skottie Young Connecting Variant...,$29.99,29.99,NaN,Brand New,Buy It Now,originstory,25900,100.0,None,6 watchers,Free returns,https://www.ebay.com/itm/236734485074
117127242187,CYBERFROG Limited Print #5 Signed and numbered...,$25.00,25.00,NaN,Brand New,Buy It Now,cyberfrog9,9100,99.8,None,None,Located in United States,https://www.ebay.com/itm/117127242187
127714730451,Kevin Nowlan's Marvel Heroes Artist's Edition ...,$30.00,30.00,NaN,Brand New,Buy It Now,pop-king,27700,99.9,None,61 watchers,Located in United States,https://www.ebay.com/itm/127714730451
146797697347,Amazing Spider-Man #261 CGC 9.6 1985,$115.00,115.00,NaN,NaN,or Best Offer,baggy_men,291,100.0,None,18 watchers,Located in United States,https://www.ebay.com/itm/146797697347
127772693759,from Sam Kieth: Darker Image #1 Image Comics 1...,$69.99,69.99,NaN,New (Other),or Best Offer,roccoscomics,3,100.0,None,None,Located in United States,https://www.ebay.com/itm/127772693759

In [8]:
queries = ["comics", "comic books", "graphic novels", "webcomics", "comic anthology"]

ebay_df = pd.DataFrame()

for query in queries:
    for page_num in range(1, 9):
        params = {
            "engine": "ebay_search",
            "q": query,
            "ebay_domain": "ebay.com",
            "num": 240,
            "page": page_num
        }

        page = requests.get(request, headers={'Authorization': f'Bearer {API_key}'}, params=params)

        if page.status_code != 200:
            break

        res = page.json()

        if "organic_results" not in res or len(res["organic_results"]) == 0:
            break

        page_df = pd.DataFrame(res["organic_results"])
        page_df = clean_page_columns(page_df)
        page_df["source_query"] = query
        page_df["source_page"] = page_num

        ebay_df = pd.concat([ebay_df, page_df])
        time.sleep(1)

In [9]:
ebay_df

,title,price,extracted_price,reviews,condition,buying_format,seller_name,seller_reviews,seller_feedback,sold_text,return_info,location,link,source_query,source_page
item_id,,,,,,,,,,,,,,,
295102178301,"LARGE 25 COMICS BOOK LOT-MARVEL, DC, INDIES- F...",$22.49,22.49,NaN,New (Other),or Best Offer,hadleycomics,1600,99.8,Save up to 10% when you buy more,"1,248 sold",Free returns,https://www.ebay.com/itm/295102178301,comics,1
376968283312,MARVEL/DC: SPIDER-MAN/SUPERMAN #1 *Dang! So Ma...,$7.89 to $89.99,NaN,NaN,Brand New,Buy It Now,odineyes_oddities,7800,100.0,20% off 20+ with coupon,Free returns,Located in United States,https://www.ebay.com/itm/376968283312,comics,1
188257989469,Dead Samurai #6 Cover C Drax Gal Cover,$5.99,5.99,NaN,New (Other),or Best Offer,torpedocomics,7700,100.0,None,None,Located in United States,https://www.ebay.com/itm/188257989469,comics,1
287039504394,DC Marvel Superman Spider-Man #1 (One Shot) Co...,$14.99,14.99,NaN,Brand New,Buy It Now,si-fi_toys,14400,99.6,None,187 sold,Free returns,https://www.ebay.com/itm/287039504394,comics,1
284701338991,lot of 100 comics 80s 90s 2000 Marvel Dc Horse...,$28.95,28.95,NaN,Pre-Owned,Buy It Now,77kings,8200,99.9,None,"1,064 sold",Located in United States,https://www.ebay.com/itm/284701338991,comics,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137208789148,Mirror Mirror 2,$27.77,27.77,NaN,Pre-Owned,Buy It Now,readingebooks,20100,99.7,None,None,Located in United States,https://www.ebay.com/itm/137208789148,comic anthology,8
406022997316,"Street Fighter 2 Comic Anthology, VG, no tears...",$99.73,99.73,NaN,New (Other),or Best Offer,kiyma87,314,99.4,None,None,Located in Japan,https://www.ebay.com/itm/406022997316,comic anthology,8
389350082654,Twilight Zone Comic #37 Gold Key May 1971 Vint...,$8.40,8.40,NaN,Pre-Owned,or Best Offer,nat_444992,24,100.0,None,None,Located in United States,https://www.ebay.com/itm/389350082654,comic anthology,8
137086011864,"The Nib Lot Issues 1-8, Death Family Empire Sc...",$94.33,94.33,NaN,Pre-Owned,or Best Offer,oregonsellerspdx,2800,99.1,None,Free returns,Located in United States,https://www.ebay.com/itm/137086011864,comic anthology,8
187866000588,Star Wars By Jason Aaron Omnibus Oop,$200.00,200.00,NaN,New (Other),or Best Offer,jacosmithso-9,200,100.0,None,None,Located in United States,https://www.ebay.com/itm/187866000588,comic anthology,8

In [ ]:
ebay_df.to_excel('ebay_comics.xlsx', index=True)